import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css'; 
import { useEffect, useState } from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>LogDog</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <div className='my-[4rem] mx-[4rem]'>
        <div className='flex w-full justify-between gap-[4rem]'>
          <div className='relative bg-white h-[50rem] w-[60%] rounded-lg'>
            <Image src='/images/home.png' alt='Home' layout='fill' objectFit='cover' className='rounded-lg' />
          </div>
          <div className='flex flex-col items-center justify-center bg-gray-200 h-[50rem] w-[40%] rounded-lg'>
            <h1 className='text-var-blue text-[3rem] font-bold my-4'>LogDog</h1>

            <p className='text-[2rem] text-center mb-[4rem] border-b-2 border-gray-400 pb-[4rem]'>
              Welcome to our Website.
              <br />
              This is a Community for pets.
              <br />
              We hope you find friends here.
            </p>
            <p className='text-[2rem] text-center'>
              'LOGDOG' 은 반려동물을 키우는 반려인을 위한 커뮤니티입니다.
              <br />
              ​초보 반려인부터 고수 반려인까지
              <br />
              모두가 반려동물이 행복하게 지낼 수 있도록
              <br />
              동물을 사랑하는 마음으로 하나가 될 수 있습니다.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
