import Head from 'next/head';
import Image from 'next/image';
import { ChangeEvent, useState } from 'react';
import SearchUI from '@/components/Search';
import ContentBox from '@/components/ContentBox';

export default function Home() {
  const [keyword, setKeyword] = useState('');
  const [isKeyword, setIsKeyword] = useState(false);
  const [isFocus, setIsFocus] = useState(false);
  const [title, setTitle] = useState('');

  const handleKeywordChange = (e: ChangeEvent<HTMLInputElement>) => {
    setKeyword(e.target.value);
    setIsKeyword(e.target.value.length > 0);
    setIsFocus(true);
  };

  const handleSubmit = () => {
    console.log('Search submitted with keyword:', keyword);
  };

  return (
    <>
      <Head>
        <title>LogDog</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <div className='my-[4rem] mx-[4rem]'>
        <div className='flex w-full justify-between gap-[4rem]'>
          <div className='relative bg-white h-[50rem] w-[60%] rounded-lg'>
            <Image src='/images/home.png' alt='Home' layout='fill' objectFit='cover' className='rounded-lg' />
          </div>
          <div className='flex flex-col items-center justify-center bg-gray-200 h-[50rem] w-[40%] rounded-lg'>
            <h1 className='text-var-blue text-[3rem] font-bold my-4'>LogDog</h1>

            <p className='text-[2rem] text-center mb-[4rem] border-b-2 border-gray-400 pb-[4rem]'>
              Welcome to our Website.
              <br />
              This is a Community for pets.
              <br />
              We hope you find friends here.
            </p>
            <p className='text-[2rem] text-center mb-4'>
              'LOGDOG' 은 반려동물을 키우는 반려인을 위한 커뮤니티입니다.
              <br />
              ​초보 반려인부터 고수 반려인까지
              <br />
              모두가 반려동물이 행복하게 지낼 수 있도록
              <br />
              동물을 사랑하는 마음으로 하나가 될 수 있습니다.
            </p>
          </div>
        </div>

        <SearchUI keyword={keyword} onChange={handleKeywordChange} onSubmit={handleSubmit} isKeyword={isKeyword} isFocus={isFocus} title={title} />

        {/* 프로젝트 소개 컨테이너 */}
        <div className='relative bg-white mt-[4rem] w-full min-h-[50rem] border border-gray-300 rounded-lg overflow-hidden'>
          {/* 배경 이미지 설정 */}
          <div className='absolute inset-0 bg-[url(/images/home_side.png)] bg-cover bg-center bg-fixed' />

          {/* 다른 요소들 위에 배치 */}
          <div className='relative z-10 flex flex-col items-center justify-center w-full h-full p-4'>
            <h1 className='text-white text-[3rem] font-bold my-4'>Our Service</h1>

            {/* 세 개의 박스를 가로로 정렬 */}
            <div className='flex gap-4 w-full max-w-screen-lg'>
              <ContentBox
                icon='/icons/twitter.svg'
                title='Self Customizing'
                text='강아지 종류와 털 색 변경 등의 커스터마이징으로 하나뿐인 아바타를 만들 수 있습니다. 캡쳐하기 버튼을 통해서 강아지를 사진으로 간직해보세요!'
              />
              <ContentBox
                icon='/icons/youtube.svg'
                title='Multi Play'
                text='강아지를 움직이면서 다른 사용자들과 채팅을 할 수 있습니다. 음성 채팅을 통한 상호작용 또한 가능하니 광장을 돌아다니면서 대화를 시작해보세요!'
              />
              <ContentBox
                icon='/icons/instagram.svg'
                title='Mini Game'
                text='​방향키 조작으로 미니 게임을 할 수 있습니다. 시간에 따라 속도가 빨라지므로 장애물을 피해서 최대한 오래 살아남으세요! 생존 시간에 따라 뼈다귀를 얻을 수 있습니다.'
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
